### ISSUE TITLE
Need HTTPS cert for production url

### ISSUE THREAD

**Issue by MoonTahoe** [MoonHighway/clam-graphql-api#45]
Netlify automatically adds an https cert to the site, so we are getting a mixed content error because the api still uses http.  Technically the website will be broken until this API supports HTTPS in production.

* [ ] Figure out how to certify sub domains under moonhighway
* [ ] Obtain necessary cert (purchase hosting if needed)
* [ ] Apply HTTPS cert to [clam-api.moonhighway.com](clam-api.moonhighway.com)

**Comment by eveporcello** [comment]
I contacted Heroku about this and should know more on Monday.

**Comment by eveporcello** [comment]
Almost there on this.

1. Set up the Hobby dyno ($7/month with SSL)
2. Set up CNAME record with GoDaddy. If you go to https://clam-api.moonhighway.com/, everything looks good.

I have a support ticket set up that will help me force HTTPS on any visit because going to http://clam-api.moonhighway.com/ doesn't reroute to https).

**Comment by MoonTahoe** [comment]
It is working... you can see it on the [account page](https://clam.moonhighway.com/account). The information on this page is coming from https...

Now one must wonder if this means that Heroku hooked up a wss for this?
